"""Build the editable and rendered revised MIT Sloan two-page paper.

The manuscript is intentionally rebuilt from the preserved historical PDF
because no editable DOCX source existed.  Scientific values are drawn from the
validated project outputs; figures are generated by the project pipeline.
"""
from pathlib import Path

from docx import Document
from docx.enum.section import WD_SECTION
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml import OxmlElement
from docx.oxml.ns import qn
from docx.shared import Cm, Inches, Pt, RGBColor


ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "paper"
FIG = ROOT / "results" / "figures"
DOCX = OUT / "Resource_Shock_Story_MIT_Sloan_Revised.docx"

BLUE = RGBColor(37, 99, 235)
DARK = RGBColor(45, 45, 45)


def set_font(run, name="Arial", size=9.2, bold=False, italic=False, color=DARK):
    run.font.name = name
    run._element.get_or_add_rPr().rFonts.set(qn("w:ascii"), name)
    run._element.get_or_add_rPr().rFonts.set(qn("w:hAnsi"), name)
    run.font.size = Pt(size)
    run.bold = bold
    run.italic = italic
    run.font.color.rgb = color


def paragraph(doc, text, size=9.2, before=0, after=4.2, align=WD_ALIGN_PARAGRAPH.JUSTIFY):
    p = doc.add_paragraph()
    p.alignment = align
    p.paragraph_format.space_before = Pt(before)
    p.paragraph_format.space_after = Pt(after)
    p.paragraph_format.line_spacing = 1.0
    p.paragraph_format.keep_together = True
    set_font(p.add_run(text), size=size)
    return p


def caption(doc, text):
    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    p.paragraph_format.space_before = Pt(2)
    p.paragraph_format.space_after = Pt(0)
    p.paragraph_format.keep_together = True
    set_font(p.add_run(text), size=7.7, italic=True, color=RGBColor(70, 70, 70))
    return p


def add_page_number(paragraph):
    paragraph.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = paragraph.add_run()
    fld_char1 = OxmlElement("w:fldChar")
    fld_char1.set(qn("w:fldCharType"), "begin")
    instr = OxmlElement("w:instrText")
    instr.set(qn("xml:space"), "preserve")
    instr.text = " PAGE "
    fld_char2 = OxmlElement("w:fldChar")
    fld_char2.set(qn("w:fldCharType"), "end")
    run._r.extend([fld_char1, instr, fld_char2])
    set_font(run, size=8.0, color=RGBColor(100, 100, 100))


def build():
    OUT.mkdir(parents=True, exist_ok=True)
    doc = Document()
    sec = doc.sections[0]
    sec.page_width = Cm(21.0)
    sec.page_height = Cm(29.7)
    sec.top_margin = Inches(0.42)
    sec.bottom_margin = Inches(0.42)
    sec.left_margin = Inches(0.55)
    sec.right_margin = Inches(0.55)
    sec.header_distance = Inches(0.18)
    sec.footer_distance = Inches(0.18)
    add_page_number(sec.footer.paragraphs[0])

    styles = doc.styles
    styles["Normal"].font.name = "Arial"
    styles["Normal"]._element.rPr.rFonts.set(qn("w:ascii"), "Arial")
    styles["Normal"]._element.rPr.rFonts.set(qn("w:hAnsi"), "Arial")

    title = doc.add_paragraph()
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    title.paragraph_format.space_after = Pt(3)
    set_font(title.add_run("Going Up, Coming Down: The Resource Shock of Promotion and Relegation\nin Spanish Football"),
             name="Georgia", size=17.5, bold=True, color=RGBColor(30, 30, 30))

    meta = doc.add_paragraph()
    meta.alignment = WD_ALIGN_PARAGRAPH.RIGHT
    meta.paragraph_format.space_after = Pt(4)
    set_font(meta.add_run("Soccer\nPaper ID: [To be assigned]"), size=8.4, color=RGBColor(70, 70, 70))

    h = doc.add_paragraph()
    h.paragraph_format.space_after = Pt(2)
    set_font(h.add_run("Abstract"), name="Georgia", size=10.5, bold=True, color=RGBColor(20, 20, 20))

    paragraph(doc,
        "Promotion is usually framed as a sporting triumph and relegation as a sporting failure, but both events also move a club overnight into a different economic neighborhood. A promoted side may spend more than ever and still arrive among the least-resourced teams in La Liga; a relegated side may lose value and yet become one of the richest teams in Segunda. We ask how crossing the La Liga-Segunda boundary changes a club's resource position relative to its new competitors, and whether that change is associated with survival or recovery.",
        size=8.65, after=3.2)
    paragraph(doc,
        "We study Spain's top two divisions across seven seasons from 2019-20 to 2025-26, covering 454 club-seasons and 18 promotion plus 18 relegation episodes, with unresolved outcomes explicitly right-censored. Our central measure is Relative Resource Position (RRP): a club's squad market value divided by the median squad market value of its division in that season. The change in RRP at promotion or relegation is the Relative Resource Shock. We combine event-time trajectories and Kaplan-Meier survival analysis with rank-biserial outcome comparisons, alternative RRP definitions, and leave-one-out sensitivity checks.",
        size=8.65, after=3.2)
    paragraph(doc,
        "Promotion was accompanied by a large relative resource shock. Median RRP fell from 1.81 in Segunda to 0.57 in La Liga, a median shock of -1.27. All 18 promoted clubs entered below the La Liga median, a pattern that is strongly structurally expected when clubs move into the substantially richer top-flight environment and is not treated as a surprising finding. More informatively, every promoted club increased its absolute squad value, with a median uplift of 78.4%, yet became substantially weaker relative to its new competitors. Relegation showed the mirror pattern: median RRP rose from 0.53 to 2.09, a shock of +1.55, even though 17 of 18 clubs lost absolute squad value.",
        size=8.65, after=3.0)

    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    p.paragraph_format.space_before = Pt(1)
    p.paragraph_format.space_after = Pt(0)
    p.paragraph_format.keep_with_next = True
    p.add_run().add_picture(str(FIG / "final_figure1_original.jpg"), width=Inches(7.02))
    caption(doc,
        "Figure 1. Dynamic Relative Resource Position around promotion and relegation. Promotion is accompanied by a shift from relative strength in Segunda to relative weakness in La Liga; relegation shows the mirror pattern.")

    doc.add_page_break()

    paragraph(doc,
        "The resource paradox is clearest when absolute and relative position are viewed together. Median La Liga survival after promotion was three seasons, and median time to return after relegation was also three seasons. Immediately relegated clubs (n=5) increased squad value by a median 39.4%, compared with 107.1% for clubs surviving at least two seasons (n=10; rank-biserial r=0.76, exploratory p=0.019). These values describe separation in this small sample rather than a causal investment effect.",
        size=9.25, after=5.0)
    paragraph(doc,
        "Higher entry RRP was strongly associated with faster return: clubs returning within two seasons (n=7) entered Segunda at median RRP 2.62, compared with 1.36 among clubs not yet returned (n=8; rank-biserial r=-0.82, exploratory p=0.006). Both headline associations remained directionally stable under leave-one-out checks. This relationship should not be interpreted causally. Squad market value may proxy for broader sporting and organizational advantages not observed in the available data, including academy quality, management continuity, ownership stability, wages, revenue, recruitment quality, parachute payments, player retention, and wider organizational capacity.",
        size=9.25, after=5.0)
    paragraph(doc,
        "For sporting directors, the practical comparison is therefore not simply whether a club became richer or poorer, but how its resources compare with the new league's norm. The study provides descriptive and exploratory evidence about resource position, survival, and recovery; it does not identify causal effects.",
        size=9.25, after=4.0)

    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    p.paragraph_format.space_before = Pt(2)
    p.paragraph_format.space_after = Pt(0)
    p.paragraph_format.keep_with_next = True
    p.add_run().add_picture(str(FIG / "final_figure2_original.jpg"), width=Inches(6.95))
    caption(doc,
        "Figure 2. The Resource Paradox. After promotion, clubs become richer in absolute squad value yet relatively weaker in La Liga; after relegation, clubs usually lose absolute value yet become relatively stronger in Segunda. These are descriptive transition patterns, not causal estimates.")

    repo = doc.add_paragraph()
    repo.alignment = WD_ALIGN_PARAGRAPH.LEFT
    repo.paragraph_format.space_before = Pt(7)
    repo.paragraph_format.space_after = Pt(0)
    set_font(repo.add_run("Open-source repository: [ANONYMIZED PUBLIC GITHUB LINK REQUIRED BEFORE SUBMISSION]"),
             size=8.0, italic=True, color=RGBColor(90, 90, 90))

    doc.core_properties.title = "Going Up Coming Down The Resource Shock of Promotion and Relegation in Spanish Football"
    doc.core_properties.subject = "MIT Sloan Sports Analytics Conference submission"
    doc.core_properties.author = ""
    doc.core_properties.last_modified_by = ""
    doc.core_properties.comments = "Revised after reviewer audit; descriptive and exploratory study."
    doc.save(DOCX)
    print(DOCX)


if __name__ == "__main__":
    build()
